[project]
name = "mcp-sentinel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "YumgNPO", email = "orumerenyerhovwo@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=2.0.0",
    "rich>=15.0.0",
    "sentence-transformers>=5.7.0",
]

[project.scripts]
mcp-sentinel = "mcp_sentinel:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
